### ISSUE TITLE
TX only on PMR466

### ISSUE THREAD

**Issue by dammh** [whosmatt/uvmod#12]
Hi and thank you so much for your work.
It is possible to add a mod for the TX that will enable transmission only on the PMR446 frequency? Thank you.

**Comment by whosmatt** [comment]
Yes that is possible, I'll look into adding it today.

**Comment by whosmatt** [comment]
I added a new mod that lets you do this. Since it modifies TX it is under the hidden mods, read the instructions to show them. 
If you use the settings below only PMR446 will work, everything else will show "DISABLED". 
![image](https://github.com/whosmatt/uvmod/assets/10769515/3558345c-c8bd-4bb7-b57b-f4465cb0ce34)
