### ISSUE TITLE
AM audio fix by OneOfEleven

### ISSUE THREAD

**Issue by krotoniec** [whosmatt/uvmod#26]
Firs of all, great work, it transforms cheap radios into something else, I truly enjoy it :)
There is some sort of an issue with AM audio quality in this radios, although OneOfEleven seems to have a fix that's working.
https://github.com/OneOfEleven/uv-k5-firmware-custom
Any chances it could be implemented in UVMOD website?

**Comment by whosmatt** [comment]
the new dev version is automatically compatible with all oefw forks, including 1o11. 
mods need to be ported though and I can't do it alone, I need contributors on this project. 

that being said, this radio will always be crap for AM. 1o11 is just a slight improvement. AM is a dirty software hack because the hardware does not support it.

**Comment by ghost** [comment]
Really hoping the UVMod website can be updated to allow for version 27
firmware as well.
