### ISSUE TITLE
File size issues with setting a custom boot image

### ISSUE THREAD

**Issue by Luporion** [whosmatt/uvmod#42]
I was trying to set a custom image for the boot screen, and got it's size down to 368 kb. 

I'm using [kamilsss655's version of the firmware](https://github.com/kamilsss655/uv-k5-firmware-custom). 

Unfortunately when i press "patch" Uvmod keeps telling me:
![image](https://github.com/whosmatt/uvmod/assets/98816560/1e558361-86ee-4a8d-8bde-cafc349c3de0)

although my file is only 
![image](https://github.com/whosmatt/uvmod/assets/98816560/14f41a0f-1551-4f9f-9f42-132bd6866be9)
big. 

Here's the picture: 
![Immanuelgemeinde Logo 128x64 px_less size_2](https://github.com/whosmatt/uvmod/assets/98816560/bd413851-68b7-4341-980b-c5f5bd62cf9e)
I created it using gimp - exactly 128x64 pixels.

So i did some calculations:
When trying to patch without my custom image, the screen shows 
![image](https://github.com/whosmatt/uvmod/assets/98816560/76a69cea-aa9b-4e48-a17c-1e6b2a7fa7ff)
meaning 60872 bytes are used.

Substract 60872 (without image) from 61896 (with the image)
61896 - 60872 = 1024 bytes
Thats exactly the max file size ![image](https://github.com/whosmatt/uvmod/assets/98816560/1b27e61c-6721-4ef6-92f6-48db851d6371)
meaning the firmware is calculated using the max filesize.

The way of calculating firmware size should be changed to the actual filesize uploaded - is that possible?

**Comment by whosmatt** [comment]
there are a few misunderstandings here:

compiled firmware does not work in uvmod because the offsets of all the symbols are never going to be the same. the same goes for different versions. i started implementing a universal patcher but its abandoned because i dont have the time. 

the image you upload is converted first since the radio does not support any file formats. the internal image format is a raw 1bit/pixel stream with the slight optimization hack where empty lines are cut from top and bottom. thats the only way you can reduce the image size with the current implementation of the bootscreen stub code. make your image black on white if alpha doesnt work. 

firmware size isnt calculated. its taken directly after patching so its always accurate.
