### ISSUE TITLE
Download updater software - security concern

### ISSUE THREAD

**Issue by ashes00** [whosmatt/uvmod#7]
Not sure if this is the best way to notify of this security issue.  However its an issue,and needs to be reported.  Upon cloning the project, and reviewing the "Download updater software" section I find that the uvk5updater.zip and embedded AnonymPSUpdater_Setup_EN.exe are lighting up VirusTotal indicating these files are malicious.  Strangely enough the MFG was the one I would be more concerned with.  It does have 1 issue, but thats an issue for them.  While I understand we do not have to use the  updater software exe itself, but having malicious executable included seems like a very bad idea.  Can someone address this concern?  Please see the VirusTotal links below for full details.

AnonymPSUpdater_Setup_EN.exe -> https://www.virustotal.com/gui/file/0872b06154e03c4ba5bddbfc153a99bd9b7a337742881b7a22dd7caf3d95d75f

uvk5updater.zip -> https://www.virustotal.com/gui/file/5f4757ed52fa0de590dee713a6dc2ccdea05c1afb2f82ff1e7c7484aa54ebddc

Thanks
Ash,

**Comment by whosmatt** [comment]
Neither of these files are malicious. Getting a hit on virustotal is very
common, and in this case you can even see that the big antivirus products
dont flag it, and all the flags it got were generic rather than specific.
Ive taken a look at heuristics and could not find anything malicious about
the updater.
